--==============================================
-- Create Database
--==============================================

USE [master]
GO

/****** Object:  Database [OCP6StoneWareDB_V3]    Script Date: 9/9/2019 7:28:05 PM ******/
CREATE DATABASE [OCP6StoneWareDB_V3]
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OCP6StoneWareDB_V3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET ARITHABORT OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET  MULTI_USER 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET QUERY_STORE = OFF
GO
USE [OCP6StoneWareDB_V3]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [OCP6StoneWareDB_V3]
GO
/****** Object:  Table [dbo].[Issue_Resolution]    Script Date: 9/9/2019 7:28:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Issue_Resolution](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[issue_id] [int] NOT NULL,
	[resolution_description] [nvarchar](3000) NOT NULL,
	[date_resolved] [date] NOT NULL,
 CONSTRAINT [PK_Issue_Resolution] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Issue_Status]    Script Date: 9/9/2019 7:28:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Issue_Status](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[status] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Issue_Status] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Issues]    Script Date: 9/9/2019 7:28:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Issues](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[product_id] [int] NOT NULL,
	[status_id] [int] NOT NULL,
	[problem_description] [nvarchar](3000) NOT NULL,
	[created_at] [date] NOT NULL,
 CONSTRAINT [PK_Issues] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Operating_Systems]    Script Date: 9/9/2019 7:28:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Operating_Systems](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Operating_Systems] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product_Detail]    Script Date: 9/9/2019 7:28:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product_Detail](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 9/9/2019 7:28:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[product_detail_id] [int] NOT NULL,
	[version_id] [int] NOT NULL,
	[os_id] [int] NOT NULL,
 CONSTRAINT [PK_Products_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Versions]    Script Date: 9/9/2019 7:28:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Versions](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[version] [numeric](2, 1) NOT NULL,
 CONSTRAINT [PK_Versions] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Issue_Resolution]  WITH CHECK ADD  CONSTRAINT [FK_Issue_Resolution_Issues] FOREIGN KEY([issue_id])
REFERENCES [dbo].[Issues] ([id])
GO
ALTER TABLE [dbo].[Issue_Resolution] CHECK CONSTRAINT [FK_Issue_Resolution_Issues]
GO
ALTER TABLE [dbo].[Issues]  WITH CHECK ADD  CONSTRAINT [FK_Issues_Products1] FOREIGN KEY([product_id])
REFERENCES [dbo].[Products] ([id])
GO
ALTER TABLE [dbo].[Issues] CHECK CONSTRAINT [FK_Issues_Products1]
GO
ALTER TABLE [dbo].[Issues]  WITH CHECK ADD  CONSTRAINT [FK_Issues_Status] FOREIGN KEY([status_id])
REFERENCES [dbo].[Issue_Status] ([id])
GO
ALTER TABLE [dbo].[Issues] CHECK CONSTRAINT [FK_Issues_Status]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Product_Details_Operating_Systems] FOREIGN KEY([os_id])
REFERENCES [dbo].[Operating_Systems] ([id])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Product_Details_Operating_Systems]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Product_Details_Versions] FOREIGN KEY([version_id])
REFERENCES [dbo].[Versions] ([id])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Product_Details_Versions]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Product_Detail] FOREIGN KEY([product_detail_id])
REFERENCES [dbo].[Product_Detail] ([id])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Product_Detail]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Relationship between Issues and Status' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Issues', @level2type=N'CONSTRAINT',@level2name=N'FK_Issues_Status'
GO
USE [master]
GO
ALTER DATABASE [OCP6StoneWareDB_V3] SET  READ_WRITE 
GO

USE [OCP6StoneWareDB_V3]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	CREATE FULLTEXT CATALOG fulltextCatalog AS DEFAULT

	CREATE FULLTEXT INDEX ON [dbo].[Issues](problem_description)
	KEY INDEX [PK_Issues]
	ON fulltextCatalog

	CREATE FULLTEXT INDEX ON [dbo].[Issue_Resolution](resolution_description)
	KEY INDEX [PK_Issue_Resolution]
	ON fulltextCatalog
END